baseURL = '/thesaurus-musicarum/'
languageCode = 'en-us'
title = 'Thesaurus Musicarum Latinarum'

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
source_author = "authors"
source_date   = "dates"

[module]
[[module.mounts]]
source = "tml-source/images"
target = "static/images"
